/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.84
 * Generated at: 2024-07-18 08:29:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.LinkedHashMap;
import com.rays.pro4.controller.TimetableListCtl;
import com.rays.pro4.Model.TimeTableModel;
import com.rays.pro4.controller.TimetableListCtl;
import com.rays.pro4.Util.DataUtility;
import com.rays.pro4.Util.HTMLUtility;
import com.rays.pro4.Bean.TimeTableBean;
import java.util.Iterator;
import java.util.List;
import com.rays.pro4.Util.ServletUtility;
import com.rays.pro4.controller.ORSView;
import com.rays.pro4.Bean.UserBean;
import com.rays.pro4.Bean.RoleBean;
import com.rays.pro4.controller.LoginCtl;
import com.rays.pro4.controller.ORSView;

public final class TimeTableListView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/jsp/Footer.jsp", Long.valueOf(1720695130582L));
    _jspx_dependants.put("/jsp/Header.jsp", Long.valueOf(1720983946039L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.rays.pro4.Bean.TimeTableBean");
    _jspx_imports_classes.add("java.util.Iterator");
    _jspx_imports_classes.add("com.rays.pro4.Bean.RoleBean");
    _jspx_imports_classes.add("com.rays.pro4.Util.DataUtility");
    _jspx_imports_classes.add("java.util.LinkedHashMap");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.rays.pro4.controller.TimetableListCtl");
    _jspx_imports_classes.add("com.rays.pro4.Model.TimeTableModel");
    _jspx_imports_classes.add("com.rays.pro4.Bean.UserBean");
    _jspx_imports_classes.add("com.rays.pro4.controller.LoginCtl");
    _jspx_imports_classes.add("com.rays.pro4.Util.ServletUtility");
    _jspx_imports_classes.add("com.rays.pro4.Util.HTMLUtility");
    _jspx_imports_classes.add("com.rays.pro4.controller.ORSView");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<link rel=\"icon\" type=\"image/png\" href=\"");
      out.print(ORSView.APP_CONTEXT);
      out.write("/img/logo.png\" sizes=\"16*16\"/>\n");
      out.write("<title> TimeTable List</title>\n");
      out.write("\n");
      out.write("  <script src=\"");
      out.print(ORSView.APP_CONTEXT );
      out.write("/js/jquery.min.js\"></script>\n");
      out.write("<script src=\"");
      out.print(ORSView.APP_CONTEXT );
      out.write("/js/Checkbox11.js\"></script>\n");
      out.write("  \n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" href=\"//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css\">\n");
      out.write("  <link rel=\"stylesheet\" href=\"/resources/demos/style.css\">\n");
      out.write("  <script src=\"https://code.jquery.com/jquery-1.12.4.js\"></script>\n");
      out.write("  <script src=\"https://code.jquery.com/ui/1.12.1/jquery-ui.js\"></script>\n");
      out.write("  \n");
      out.write("  \n");
      out.write(" \n");
      out.write("\n");
      out.write("  <script>\n");
      out.write("  \n");
      out.write("  function disableSunday(d){\n");
      out.write("	  var day = d.getDay();\n");
      out.write("	  if(day==0)\n");
      out.write("	  {\n");
      out.write("	   return [false];\n");
      out.write("	  }else\n");
      out.write("	  {\n");
      out.write("		  return [true];\n");
      out.write("	  }\n");
      out.write("  }\n");
      out.write("  \n");
      out.write("  $( function() {\n");
      out.write("	  $( \"#abcd\" ).datepicker({\n");
      out.write("		  changeMonth :true,\n");
      out.write("		  changeYear :true,\n");
      out.write("		  yearRange :'0:+10',\n");
      out.write("		  dateFormat:'dd-mm-yy',\n");
      out.write("\n");
      out.write("// Disable for Sunday\n");
      out.write("		  beforeShowDay : disableSunday,		  \n");
      out.write("// Disable for back date\n");
      out.write("		  minDate : 0   \n");
      out.write("	  });\n");
      out.write("  } );\n");
      out.write("  </script>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body >\n");
      com.rays.pro4.Bean.TimeTableBean bean = null;
      bean = (com.rays.pro4.Bean.TimeTableBean) _jspx_page_context.getAttribute("bean", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (bean == null){
        bean = new com.rays.pro4.Bean.TimeTableBean();
        _jspx_page_context.setAttribute("bean", bean, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\n');
      out.write("<!DOCTYPE html>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("	");

		UserBean userBean = (UserBean) session.getAttribute("user");
		boolean userLoggedIn = userBean != null;
		String welcomeMsg = "Hi, ";
		if (userLoggedIn) {
			String role = (String) session.getAttribute("role");
			welcomeMsg += userBean.getFirstName() + " (" + role + ")";
		} else {
			welcomeMsg += "Guest";
		}
	
      out.write("\n");
      out.write("\n");
      out.write("	<table>\n");
      out.write("		<tr>\n");
      out.write("			<th></th>\n");
      out.write("			<td width=\"90%\"><a href=\"");
      out.print(ORSView.WELCOME_CTL);
      out.write("\">Welcome</b></a> |\n");
      out.write("				");

				if (userLoggedIn) {
			
      out.write(" <a\n");
      out.write("				href=\" ");
      out.print(ORSView.LOGIN_CTL);
      out.write("?operation=");
      out.print(LoginCtl.OP_LOG_OUT);
      out.write("\">Logout</b></a>\n");
      out.write("\n");
      out.write("				");

					} else {
				
      out.write(" <a href=\"");
      out.print(ORSView.LOGIN_CTL);
      out.write("\">Login</b></a> ");

 	}
 
      out.write("</td>\n");
      out.write("			<td rowspan=\"2\">\n");
      out.write("				<h1 align=\"right\">\n");
      out.write("					<img src=\"");
      out.print(ORSView.APP_CONTEXT);
      out.write("/img/customLogo.jpg\" width=\"175\"\n");
      out.write("						height=\"50\">\n");
      out.write("				</h1>\n");
      out.write("			</td>\n");
      out.write("		</tr>\n");
      out.write("\n");
      out.write("		<tr>\n");
      out.write("			<th></th>\n");
      out.write("			<td>\n");
      out.write("				<h3>");
      out.print(welcomeMsg);
      out.write("</h3>\n");
      out.write("			</td>\n");
      out.write("		</tr>\n");
      out.write("\n");
      out.write("		");

			if (userLoggedIn) {
		
      out.write("\n");
      out.write("\n");
      out.write("		<tr>\n");
      out.write("			<th></th>\n");
      out.write("			<td colspan=\"2\"><font style=\"font-size: 18px\"> <a\n");
      out.write("					href=\"");
      out.print(ORSView.MY_PROFILE_CTL);
      out.write("\">MyProfile</b></a> | <a\n");
      out.write("					href=\"");
      out.print(ORSView.CHANGE_PASSWORD_CTL);
      out.write("\">Change Password</b></a> | <a\n");
      out.write("					href=\"");
      out.print(ORSView.GET_MARKSHEET_CTL);
      out.write("\">Get Marksheet</b></a> | <a\n");
      out.write("					href=\"");
      out.print(ORSView.MARKSHEET_MERIT_LIST_CTL);
      out.write("\">Marksheet\n");
      out.write("						MeritList</b>\n");
      out.write("				</a> | ");

					if (userBean.getRoleId() == RoleBean.ADMIN) {
				
      out.write(" <a href=\"");
      out.print(ORSView.MARKSHEET_CTL);
      out.write("\">Add Marksheet</b></a> | <a\n");
      out.write("					href=\"");
      out.print(ORSView.MARKSHEET_LIST_CTL);
      out.write("\">Marksheet List</b></a> | <a\n");
      out.write("					href=\"");
      out.print(ORSView.USER_CTL);
      out.write("\">Add User</b></a> | <a\n");
      out.write("					href=\"");
      out.print(ORSView.USER_LIST_CTL);
      out.write("\">User List</b></a> | <a\n");
      out.write("					href=\"");
      out.print(ORSView.COLLEGE_CTL);
      out.write("\">Add College</b></a> | <a\n");
      out.write("					href=\"");
      out.print(ORSView.COLLEGE_LIST_CTL);
      out.write("\">College List</b></a> | <a\n");
      out.write("					href=\"");
      out.print(ORSView.ROLE_CTL);
      out.write("\">Add Role</b></a> | <a\n");
      out.write("					href=\"");
      out.print(ORSView.ROLE_LIST_CTL);
      out.write("\">Role List</b></a> | <br> <a\n");
      out.write("					href=\"");
      out.print(ORSView.STUDENT_CTL);
      out.write("\">Add Student</b></a> | <a\n");
      out.write("					href=\"");
      out.print(ORSView.STUDENT_LIST_CTL);
      out.write("\">Student List</b></a> | <a\n");
      out.write("					href=\"");
      out.print(ORSView.COURSE_CTL);
      out.write("\">Add Course</b></a> | <a\n");
      out.write("					href=\"");
      out.print(ORSView.COURSE_LIST_CTL);
      out.write("\">Course List</b></a> | <a\n");
      out.write("					href=\"");
      out.print(ORSView.SUBJECT_CTL);
      out.write("\">Add Subject</b></a> | <a\n");
      out.write("					href=\"");
      out.print(ORSView.SUBJECT_LIST_CTL);
      out.write("\">Subject List</b></a> | <a\n");
      out.write("					href=\"");
      out.print(ORSView.FACULTY_CTL);
      out.write("\">Add Faculty</b></a> | <a\n");
      out.write("					href=\"");
      out.print(ORSView.FACULTY_LIST_CTL);
      out.write("\">Faculty List</b></a> | <a\n");
      out.write("					href=\"");
      out.print(ORSView.TIMETABLE_CTL);
      out.write("\">Add TimeTable</b></a> | <a\n");
      out.write("					href=\"");
      out.print(ORSView.TIMETABLE_LIST_CTL);
      out.write("\">TimeTable List</b></a> | <a\n");
      out.write("					href=\"");
      out.print(ORSView.PRODUCT_CTL);
      out.write("\">Add Customer</a> | <a\n");
      out.write("					href=\"");
      out.print(ORSView.PRODUCT_LIST_CTL);
      out.write("\">Product List</a> | <a\n");
      out.write("					target=\"blank\" href=\"");
      out.print(ORSView.JAVA_DOC_VIEW);
      out.write("\">Java Doc</b></a> | ");

 	}
 
      out.write(' ');

 	if (userBean.getRoleId() == RoleBean.STUDENT) {
 
      out.write(" <a href=\"");
      out.print(ORSView.COLLEGE_LIST_CTL);
      out.write("\">College List</b></a> | <a\n");
      out.write("					href=\"");
      out.print(ORSView.STUDENT_LIST_CTL);
      out.write("\">Student List</b></a> | <a\n");
      out.write("					href=\"");
      out.print(ORSView.COURSE_LIST_CTL);
      out.write("\">Course List</b></a> | <a\n");
      out.write("					href=\"");
      out.print(ORSView.SUBJECT_LIST_CTL);
      out.write("\">Subject List</b></a> | <a\n");
      out.write("					href=\"");
      out.print(ORSView.FACULTY_LIST_CTL);
      out.write("\">Faculty List</b></a> | <a\n");
      out.write("					<a href=\"");
      out.print(ORSView.PRODUCT_LIST_CTL);
      out.write("\">Product List</a> |\n");
      out.write("					\n");
      out.write("					href=\"");
      out.print(ORSView.TIMETABLE_LIST_CTL);
      out.write("\">TimeTable\n");
      out.write("						List</b>\n");
      out.write("				</a> | ");

					}
				
      out.write(' ');

 	if (userBean.getRoleId() == RoleBean.KIOSK) {
 
      out.write(" <a href=\"");
      out.print(ORSView.COLLEGE_LIST_CTL);
      out.write("\">College List</b></a> | <a\n");
      out.write("					href=\"");
      out.print(ORSView.TIMETABLE_LIST_CTL);
      out.write("\">TimeTable List</b></a> | <a\n");
      out.write("					href=\"");
      out.print(ORSView.COURSE_LIST_CTL);
      out.write("\">Course List</b></a> | ");

 	}
 
      out.write(' ');

 	if (userBean.getRoleId() == RoleBean.FACULTY) {
 			// System.out.println("======>><><>"+userBean.getRoleId());
 
      out.write(" <a href=\"");
      out.print(ORSView.MARKSHEET_CTL);
      out.write("\">Add Marksheet</b></a> | <a\n");
      out.write("					href=\"");
      out.print(ORSView.MARKSHEET_LIST_CTL);
      out.write("\">Marksheet List</b></a> | <a\n");
      out.write("					href=\"");
      out.print(ORSView.COLLEGE_LIST_CTL);
      out.write("\">College List</b></a> | <a\n");
      out.write("					href=\"");
      out.print(ORSView.STUDENT_CTL);
      out.write("\">Add Student</b></a> | <a\n");
      out.write("					href=\"");
      out.print(ORSView.STUDENT_LIST_CTL);
      out.write("\">Student List</b></a> | <a\n");
      out.write("					href=\"");
      out.print(ORSView.COURSE_LIST_CTL);
      out.write("\">Course List</b></a> | <a\n");
      out.write("					href=\"");
      out.print(ORSView.SUBJECT_CTL);
      out.write("\">Add Subject</b></a> | <br> <a\n");
      out.write("					href=\"");
      out.print(ORSView.SUBJECT_LIST_CTL);
      out.write("\">Subject List</b></a> | <a\n");
      out.write("					href=\"");
      out.print(ORSView.TIMETABLE_CTL);
      out.write("\">Add TimeTable</b></a> | <a\n");
      out.write("					href=\"");
      out.print(ORSView.TIMETABLE_LIST_CTL);
      out.write("\">TimeTable List</b></a> | ");

 	}
 
      out.write(' ');

 	if (userBean.getRoleId() == RoleBean.COLLEGE) {
 			//    System.out.println("======>><><>"+userBean.getRoleId());
 
      out.write(" <a href=\"");
      out.print(ORSView.MARKSHEET_CTL);
      out.write("\">Add Marksheet</b></a> | <a\n");
      out.write("					href=\"");
      out.print(ORSView.MARKSHEET_LIST_CTL);
      out.write("\">Marksheet List</b></a> | <a\n");
      out.write("					href=\"");
      out.print(ORSView.STUDENT_CTL);
      out.write("\">Add Student</b></a> | <a\n");
      out.write("					href=\"");
      out.print(ORSView.STUDENT_LIST_CTL);
      out.write("\">Student List</b></a> | <a\n");
      out.write("					href=\"");
      out.print(ORSView.FACULTY_LIST_CTL);
      out.write("\">Faculty List</b></a> | <a\n");
      out.write("					href=\"");
      out.print(ORSView.TIMETABLE_LIST_CTL);
      out.write("\">TimeTable List</b></a> | <a\n");
      out.write("					href=\"");
      out.print(ORSView.COURSE_LIST_CTL);
      out.write("\">Course List</b></a> | ");

 	}
 
      out.write("\n");
      out.write("\n");
      out.write("			</font></td>\n");
      out.write("		</tr>\n");
      out.write("		");

			}
		
      out.write("\n");
      out.write("	</table>\n");
      out.write("	<hr>\n");
      out.write("</body>\n");
      out.write("</html>");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<form action=\"");
      out.print(ORSView.TIMETABLE_LIST_CTL );
      out.write("\" method=\"post\"> \n");
      out.write("	\n");
      out.write("	<center>\n");
      out.write("		\n");
      out.write("	<div align=\"center\">\n");
      out.write("	<h1>TimeTable List</h1>\n");
      out.write("	\n");
      out.write("	<h3>\n");
      out.write("	\n");
      out.write("		<font style=\"font: bold ; color: red\">");
      out.print(ServletUtility.getErrorMessage(request) );
      out.write("</font>	\n");
      out.write("		<font style=\"font: bold ; color: green\">");
      out.print(ServletUtility.getSuccessMessage(request) );
      out.write("</font>	\n");
      out.write("	</h3>\n");
      out.write("	</div>\n");
      out.write("	\n");
      out.write("	");

		List cList = (List) request.getAttribute("courseList");
	
		List sList = (List) request.getAttribute("subjectList"); 
		
		List eList = (List) request.getAttribute("examtime"); 

		
		int next=DataUtility.getInt(request.getAttribute("nextlist").toString());

		
		
      out.write('\n');
      out.write('	');

	int pageNo = ServletUtility.getPageNo(request);
	int pageSize = ServletUtility.getPageSize(request);	
	int index = ((pageNo-1)*pageSize)+1;

	List list = ServletUtility.getList(request);
	Iterator<TimeTableBean> it = list.iterator();
	 
	if(list.size() !=0){

	
      out.write("\n");
      out.write("	\n");
      out.write("	<table width =\"100%\">\n");
      out.write("		<tr>\n");
      out.write("		<td align=\"center\">\n");
      out.write("		<label>Course Name :</label>\n");
      out.write("		");
      out.print(HTMLUtility.getList("clist", String.valueOf(bean.getCourseId()), cList) );
      out.write("\n");
      out.write("		\n");
      out.write("		<label>Subject Name :</label>\n");
      out.write("		");
      out.print(HTMLUtility.getList("slist", String.valueOf(bean.getSubjectId()), sList) );
      out.write("\n");
      out.write("		\n");
      out.write("		");
      out.write('\n');
      out.write('	');
      out.write('	');
      out.write("\n");
      out.write("	\n");
      out.write("	\n");
      out.write("	\n");
      out.write("	 ");
      out.write("\n");
      out.write("				 \n");
      out.write("				\n");
      out.write("			<input type=\"submit\" name=\"operation\" value=\"");
      out.print(TimetableListCtl.OP_SEARCH);
      out.write("\">\n");
      out.write("		&nbsp;\n");
      out.write("		<input type=\"submit\" name=\"operation\" value=\"");
      out.print(TimetableListCtl.OP_RESET );
      out.write("\">\n");
      out.write("		\n");
      out.write("		</td>	\n");
      out.write("		</tr>\n");
      out.write("	</table>\n");
      out.write("<br>	\n");
      out.write("	<table border=\"1\" width=\"100%\" align=\"center\" cellpadding=6px cellspacing=\".2\">\n");
      out.write("		<tr style=\"background: skyblue\">\n");
      out.write("		\n");
      out.write("			<th width=\"5%\"><input type=\"checkbox\" id=\"select_all\" name =\"Select\">Select All.</th>\n");
      out.write("			<th>S.No.</th>	\n");
      out.write("			<th>Course Name.</th>\n");
      out.write("			<th>Subject Name.</th>\n");
      out.write("			<th>Semester.</th>\n");
      out.write("			<th>ExamDate.</th>\n");
      out.write("			<th>ExamTime.</th>\n");
      out.write("			<th>Edit</th>\n");
      out.write("			\n");
      out.write("		</tr>\n");
      out.write("	");

	while(it.hasNext()){
	bean =it.next();	
	
      out.write("\n");
      out.write("	<tr align=\"center\">\n");
      out.write("		<td><input type = \"checkbox\" class=\"checkbox\" name=\"ids\" value=\"");
      out.print(bean.getId() );
      out.write("\"></td>\n");
      out.write("		<td>");
      out.print(index++ );
      out.write("</td>\n");
      out.write("		<td>");
      out.print(bean.getCourseName() );
      out.write("</td>\n");
      out.write("		<td>");
      out.print(bean.getSubjectName() );
      out.write("</td>\n");
      out.write("		<td>");
      out.print(bean.getSemester() );
      out.write("</td>\n");
      out.write("		<td>");
      out.print(bean.getExamDate() );
      out.write("</td>\n");
      out.write("		<td>");
      out.print(bean.getExamTime() );
      out.write("</td>\n");
      out.write("		<td><a href =\"TimeTableCtl?id=");
      out.print(bean.getId());
      out.write("\">Edit</a></td>\n");
      out.write("	</tr>\n");
      out.write("		");
 
		}
		
      out.write("\n");
      out.write("	</table>\n");
      out.write("\n");
      out.write("	<table width = \"100%\">\n");
      out.write("		<tr><th></th>\n");
      out.write("			");
if(pageNo==1){ 
      out.write("\n");
      out.write("			<td align=\"left\"><input type=\"submit\" name=\"operation\" disabled=\"disabled\" value=\"");
      out.print(TimetableListCtl.OP_PREVIOUS);
      out.write("\" ></td>\n");
      out.write("			");
}else{ 
      out.write("\n");
      out.write("			<td align=\"left\"><input type=\"submit\" name=\"operation\" value=\"");
      out.print(TimetableListCtl.OP_PREVIOUS);
      out.write("\" ></td>\n");
      out.write("			");
} 
			
      out.write("\n");
      out.write("			\n");
      out.write("			<td><input type=\"submit\" name=\"operation\" value=\"");
      out.print(TimetableListCtl.OP_DELETE);
      out.write("\"></td>\n");
      out.write("			<td><input type=\"submit\" name=\"operation\" value=\"");
      out.print(TimetableListCtl.OP_NEW);
      out.write("\"></td>	\n");
      out.write("			\n");
      out.write("				");

					TimeTableModel model = new TimeTableModel();
				
      out.write("\n");
      out.write("			\n");
      out.write("		");
      out.write("\n");
      out.write("			\n");
      out.write("			<td align=\"right\"><input type=\"submit\"  name=\"operation\" value=\"");
      out.print(TimetableListCtl.OP_NEXT);
      out.write('"');
      out.write(' ');
      out.print((list.size()<pageSize||next==0)?"disabled":"" );
      out.write("> </td>\n");
      out.write("			\n");
      out.write("		</tr>\n");
      out.write("	</table>\n");
      out.write("	\n");
      out.write("					");
}if(list.size() == 0){ 
      out.write("\n");
      out.write("            		<td align=\"center\"><input type=\"submit\" name=\"operation\" value=\"");
      out.print(TimetableListCtl.OP_BACK);
      out.write("\"></td>	\n");
      out.write("            		");
 } 
      out.write("\n");
      out.write("            \n");
      out.write("	\n");
      out.write("		<input type=\"hidden\" name=\"pageNo\" value=\"");
      out.print(pageNo );
      out.write("\">\n");
      out.write("		<input type=\"hidden\" name=\"pageSize\" value=\"");
      out.print(pageSize);
      out.write("\">\n");
      out.write("</form>\n");
      out.write("</br>\n");
      out.write("</br>\n");
      out.write("</br>\n");
      out.write("                   </br>\n");
      out.write("                   </br>\n");
      out.write("                   </br>\n");
      out.write("</center>\n");
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("\n");
      out.write("  <style type=\"text/css\">\n");
      out.write("#footer {\n");
      out.write("    \n");
      out.write("    position: fixed;\n");
      out.write("    left:0;\n");
      out.write("    width:100%; \n");
      out.write("    bottom:0;\n");
      out.write("    background-color:white;\n");
      out.write("    color:black;\n");
      out.write("   \n");
      out.write("   \n");
      out.write("   text-align:center;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write(" \n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<div id =\"footer\">\n");
      out.write("<CENTER><hr>\n");
      out.write("    <H3>&copy; Copyrights RAYS Technologies</H3>\n");
      out.write("</CENTER>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("</html>");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
